services:
  - type: web
    name: moodbeats-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 10000

  - type: web
    name: moodbeats-frontend
    env: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build

